- id: verde
  name: verde
  description: "Verde: a Python formatter forked from Black"
  entry: verde
  language: python
  minimum_pre_commit_version: 2.9.2
  require_serial: true
  types_or: [python, pyi]
